repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: flake8
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.2
    hooks:
      - id: shell-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.5
    hooks:
      - id: remove-tabs
        exclude: ^Makefile$
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
      - id: reorder-python-imports
  - repo: local
    hooks:
      - id: remove-unicode-non-breaking-spaces
        name: Remove unicode non-breaking space character U+00A0 aka M-BM-
        language: system
        entry: perl -pi* -e 's/\xc2\xa0/ /g && ($t = 1) && print STDERR $_; END{{exit $t}}'
        files: ''
      - id: remove-en-dashes
        name: Remove the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -pi* -e 's/\xe2\x80\x93/-/g && ($t = 1) && print STDERR $_; END{{exit $t}}'
        files: ''
